travis:
  secure:
    BINSTAR_TOKEN: Hp3lpnoVPNs3mbPy78kbj2WwltwWYn4+qmonYB6ZF22Fo+cleJe+ef2e4o63J8+VtTRDVt9Ryp7ypJl0KaDRqcHt2gJMWH5dscjS4JWCRZj11uhTCfXhT5N2R9EU+ToLRyUFP77CbWb8uJaZeDHbJtFmOk1RiMPTBsFrwwfzyC0dBKouWTMZtL/Q62oxiDzlHJw8CS3Yyf4KrVemgHar5Yp6Z5C/lq9y2mHUJ4gzSChm89syWqI/DAobtDYCrK3gcDw4RtoSWLsRHP4v4KUqAyRWdX2uSFsjuYUrwPiJ70RlhPwjUZmbArqAVTk2jEgtptF1hXyyzXZ79h78ET8s2QVYsSaf5dgprKT1IT/+LeLugQRCz6QJvSwfzDHwhoHF+a5mbPen3eSL59tHx8CPmlDn3q3JXU6aEqdYBNEJ4891th6q7+VbV2/LzT7UTvUpNSXaeANWQi28M2h94Je1HceW55UBRRfVmP+ucdLmg+1Ox74ObGDSiU/WpE+YRfYwLJmSpduH1OdS+zxp6Ciww9mfdz7vW6ZsJr8aixFyGS9N+NteI0KEFKNn6JJMwdckXC7FsZ1lQDnYEMMgO9MUFdsyJUQFfqpFr691tBSCwIXgSBQjSpGWZvKN+oM5eeQgT7mA4eLuZroZWCzoTR/UkFzAW0zTe3tJrcEErIA3/6w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
